### ISSUE TITLE
tuxonice-4.12 does not compile: implicit declaration of function get_swap_range_of_type

### ISSUE THREAD

**Issue by hjudt** [NigelCunningham/tuxonice-kernel-old#33]
kernel/power/tuxonice_swap.c: In function "toi_swap_allocate_storage":
kernel/power/tuxonice_swap.c:241:7: error: implicit declaration of function "get_swap_range_of_type" [-Werror=implicit-function-declaration]
       get_swap_range_of_type(chain->allocator_index, &start, &end,
       ^~~~~~~~~~~~~~~~~~~~~~

**Comment by hjudt** [comment]
Ok, I see:
3cb542f32f6a - Apply TuxOnIce to 4.12. Not ready yet. (5 days ago) <Nigel Cunningham>

**Comment by NigelCunningham** [comment]
Hi again Harald.

Would you send me your kernel config, please? I'm unable to reproduce the issue here at the moment.

Thanks!

**Comment by hjudt** [comment]
Since I can't upload the file here, please take it from this link: https://pastebin.com/yPAzPkBd

**Comment by ManuelKrause** [comment]
@hjudt:
With a fresh github account I can even leave an aswer on here directly. :-)
I'm currently reviewing Nigel's 4.12-TOI code or merely comparing it with my working port. For YOUR issue please try this patch:  https://workupload.com/file/5VuGakQ
I have no idea, why Nigel always omits it.

BR, Manuel Krause

**Comment by hjudt** [comment]
@ManuelKrause Thanks, this fixed compilation. So far, tuxonice seems to work fine! It's good to finally have it back, with 4.11 it didn't work for me, while vanilla hibernation did.

**Comment by ManuelKrause** [comment]
@hjudt:
Thank you for reporting back and I hope it works well for you. I'm only at followup hibernation No.3 without reboot, so far, and thus need more testing. I've now taken over all of Nigel's code + the patch above.
Although it seems better than my trial-port for 4.12, I'm not convinced of it's reliability: At this actual 3rd resume it took 6 attempts to get it past "Atomic copy/restore", otherwise hanging there. Unfortunately I already know this from my system but not the cause.

BR, Manuel Krause

**Comment by mschlaeffer** [comment]
@ManuelKrause:
Regarding your question why Nigel omits your patch: I suggest to prepare a git branch on github for each kernel version, which contains only your patch and is rebased on Nigel's tuxonice-4.x branches. This would make it much easier for Nigel to include your improvements. Furthermore, I would also be interested and could test your patches.

**Comment by ManuelKrause** [comment]
@mschlaeffer:
We already know us from previous mails. :-) Hi, again!
To be honest, I'm completely new to github, and the git stuff I had done earlier is unfortunately forgotten. Regarding your proposal, 1st I don't want to have a bunch of git kernels hogging my disk, and 2nd I don't know where to begin. Furthermore, Nigel's branches had some serious sync lagging during the last months vs. torvalds -- but luckily this is gone atm. due to his heavy work to actualise and expose more trees/branches. And, 3rd as I'm no programmer, maintaining an extra TOI github of my own is overkill, IMO.

Regarding Nigel's 4.12 "tuxonice-4.12" of this moment, only the patch I've linked above is needed to make it compile, it's for swap hibernation. 
I've already had some email dialogue about this at 4.11 times and I've gotten confused, too, and maybe he's now feeling threatened by my amateurishness. @Nigel: Sorry for that!

**Comment by NigelCunningham** [comment]
Morning guys.

Great to see your discussion and interest in getting a working ToI for 4.12!

The only reason I haven't gotten there yet is the usual one - I'm spreading myself too thin. I did start to reimplement the get_swap_range_of_type (name is from memory) function for 4.12, but that was when I hadn't yet been shown that it was just a mismerge that resulted in it not being there. I'll apply the patch above as soon as I'm able.

Manuel, no problem with your patch - I'm glad you're giving it a go!

Humble apologies again for my slowness!

Nigel

**Comment by hjudt** [comment]
This has already been fixed, so closing.
